# Generated by Django 6.0.3 on 2026-03-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('command_type', models.CharField(choices=[('message', 'Message'), ('move', 'Move'), ('stop', 'Stop'), ('follow', 'Follow'), ('formation', 'Formation'), ('attack', 'Attack Pattern')], default='message', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
